name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: constitution.tex
            
      - name: Save PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Constitution PDF
          path: constitution.pdf
